version: "3.9"

services:
    db:
        image: mysql:8
        cap_add:
            - SYS_NICE
        volumes:
            - sdi-mysql-data:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --general-log=1 --general-log-file=/var/log/mysql/general-log.log
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wxweather
        ports:
            - 8003:3306

    weather-tracker-server:
        build: .
        stdin_open: true
        ports:
            - 8000:8000
            - 8001:8001
        working_dir: /code
        volumes:
            - ./src/:/code
        environment:
            MYSQL_HOST: db
            MYSQL_USER: root
            MYSQL_PASSWORD: password
        depends_on:
            - db
volumes:
    sdi-mysql-data: