name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      # Configure pip to cache dependencies
      PIP_NO_CACHE_DIR: false

      # Make sure package manager does not use virtualenv
      POETRY_VIRTUALENVS_CREATE: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        id: python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      # Install our dependencies
      - name: Install dependencies using poetry
        run: |
          pip install poetry
          poetry install
      # We will not run `flake8`, `black`, or `isort` here, as we will use a
      # separate actions. As pre-commit does not support user installs, we set
      # PIP_USER=0 to not do a user install.
      - name: Run pre-commit hooks
        run: SKIP=black,isort pre-commit run --all-files

      # Run Black using it's provided GitHub action
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --diff"

      # Run isort using it's provided GitHub action
      - name: Run isort
        uses: jamescurtin/isort-action@master
        with:
          configuration: "--gitignore --check --diff"
